apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::036292124076:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1QS9QB1D0C8BT
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-11-23T10:03:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1567"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 7223af3f-e094-4434-bdd1-d2adbc1b9663
