apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::036292124076:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-869TCAYZIY6F
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-11-27T15:49:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1466"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid:  ce91427d-a01d-4849-8c6a-8ecb867da4a9
